version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blog-postgres
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./blog-platform-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: blog-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      APP_SECURITY_JWT_SECRET: Crazy Fredrick bought many very exquisite opal jewels just to flex
      APP_SECURITY_JWT_ACCESS_EXP_MIN: 15
      APP_SECURITY_JWT_REFRESH_EXP_DAYS: 7
