spring:
  application:
    name: blog-platform

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    com.souvanik.blog: DEBUG
