spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: never

app:
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET}
      access-token-expiry-minutes: ${APP_SECURITY_JWT_ACCESS_EXP_MIN}
      refresh-token-expiry-days: ${APP_SECURITY_JWT_REFRESH_EXP_DAYS}

logging:
  level:
    root: INFO
    com.souvanik.blog: INFO

springdoc:
  swagger-ui:
    enabled: false
